### ISSUE TITLE
testing the pruning

### ISSUE THREAD

**Issue by danpovey** [danpovey/pocolm#15]
OK, prune_lm_dir.py is now working; there is an example of its use in egs/self_test/.
Testing is needed now, and comparisons with other toolkits' pruning methods.
Unfortunately, getting the perplexity on the dev data still requires conversion to SRILM.  I'll work on a native way to do that.

**Comment by vince62s** [comment]
throwing an error
float-counts-prune.cc:433: float pocolm::FloatCountsPruner::PruningLogprobChange(float, float, float, float): Assertion `ans < 0.0001 \* (count + discount)' failed.

cmdline is : prune_lm_dir.py data/lm_150000_3 4.0 data/lm_150000_3_pruned4.0

**Comment by danpovey** [comment]
Can you get that program in gdb and figure out ans, count and discount?  I
may have to change the threshold.
Dan

**Comment by danpovey** [comment]
BTW, you can probably just change the threshold, e.g. to 0.001, or change
the < to <= if there are zeros involved.  That was just a check on the
math, but it could be an error caused by roundoff.

**Comment by danpovey** [comment]
Forget this- I just pushed a change which should fix this issue.

**Comment by vince62s** [comment]
next one lm-state.cc:251
similar

**Comment by danpovey** [comment]
See if you can get more details on the exact numbers, it may clarify
whether it's a tolerance issue or an actual  bug.

**Comment by danpovey** [comment]
It's OK, I fixed this.

**Comment by vince62s** [comment]
you did not change lm-state.cc did you ? still assertion error at 251

**Comment by danpovey** [comment]
No but I changed some other code.  Show me some output, I want to see what
happens before that.

**Comment by vince62s** [comment]
float-counts-prune: aside from unigram there were 54633092 nonzero n-grams.
Of these 923112 were not pruned because they were shadowed by a higher-order n-gram, and
146733 because they lead to an existing LM-state (according to <protected-counts-input>).
Of the 53563247 n-grams eligible for pruning, 47339070 were actually pruned.
merge-float-counts data/lm_150000_3_pruned4.0/work/iter1/float.1 data/lm_150000_3_pruned4.0/work/iter1/float.2 data/lm_150000_3_pruned4.0/work/iter1/float.3 | float-counts-stats-remove-zeros 150000 /dev/stdin data/lm_150000_3_pruned4.0/work/iter0/stats.all data/lm_150000_3_pruned4.0/work/iter1/float.all data/lm_150000_3_pruned4.0/work/iter1/stats.1 data/lm_150000_3_pruned4.0/work/iter1/stats.2 data/lm_150000_3_pruned4.0/work/iter1/stats.3
float-counts-stats-remove-zeros: lm-state.cc:251: void pocolm::FloatLmState::Check() const: Assertion `fabs(total - my_total) <= 0.0001 \* fabs(my_total)' failed.
Failure writing FloatLmState to stream
sh: line 1:  2008 Done(1)                 merge-float-counts data/lm_150000_3_pruned4.0/work/iter1/float.1 data/lm_150000_3_pruned4.0/work/iter1/float.2 data/lm_150000_3_pruned4.0/work/iter1/float.3
      2009 Aborted                 (core dumped) | float-counts-stats-remove-zeros 150000 /dev/stdin data/lm_150000_3_pruned4.0/work/iter0/stats.all data/lm_150000_3_pruned4.0/work/iter1/float.all data/lm_150000_3_pruned4.0/work/iter1/stats.1 data/lm_150000_3_pruned4.0/work/iter1/stats.2 data/lm_150000_3_pruned4.0/work/iter1/stats.3
get_objf_and_derivs_split.py: error running command: merge-float-counts data/lm_150000_3_pruned4.0/work/iter1/float.1 data/lm_150000_3_pruned4.0/work/iter1/float.2 data/lm_150000_3_pruned4.0/work/iter1/float.3 | float-counts-stats-remove-zeros 150000 /dev/stdin data/lm_150000_3_pruned4.0/work/iter0/stats.all data/lm_150000_3_pruned4.0/work/iter1/float.all data/lm_150000_3_pruned4.0/work/iter1/stats.1 data/lm_150000_3_pruned4.0/work/iter1/stats.2 data/lm_150000_3_pruned4.0/work/iter1/stats.3

**Comment by danpovey** [comment]
Thanks... committed a further fix.

**Comment by vince62s** [comment]
not yet ....

validate_vocab.py: validated file data/lm_150000_3/words.txt with 150000 entries.
validate_lm_dir.py: validated LM directory data/lm_150000_3
float-counts-to-histories <data/lm_150000_3_pruned4.0/work/iter0/float.all | LC_ALL=C sort | histories-to-null-counts >data/lm_150000_3_pruned4.0/work/iter0/protected.all
float-counts-to-histories: printed 9832770 histories (out of 9832771 in total).
histories-to-null-counts: processed 149498 LM states, with 9832770 individual n-grams.
float-counts-to-float-stats 150000 data/lm_150000_3_pruned4.0/work/iter0/stats.1 data/lm_150000_3_pruned4.0/work/iter0/stats.2 data/lm_150000_3_pruned4.0/work/iter0/stats.3 <data/lm_150000_3_pruned4.0/work/iter0/float.all
merge-float-counts data/lm_150000_3_pruned4.0/work/iter0/stats.1 data/lm_150000_3_pruned4.0/work/iter0/stats.2 data/lm_150000_3_pruned4.0/work/iter0/stats.3 > data/lm_150000_3_pruned4.0/work/iter0/stats.all
merge-float-counts: read 1 + 149999 + 9682771 = 9.83277e+06 LM states.
rm data/lm_150000_3_pruned4.0/work/iter0/stats.1 data/lm_150000_3_pruned4.0/work/iter0/stats.2 data/lm_150000_3_pruned4.0/work/iter0/stats.3
float-counts-estimate 150000 data/lm_150000_3_pruned4.0/work/iter0/float.all data/lm_150000_3_pruned4.0/work/iter0/stats.all /dev/null /dev/null /dev/null 
float-counts-prune 1.0 150000 data/lm_150000_3_pruned4.0/work/iter0/float.all data/lm_150000_3_pruned4.0/work/iter0/protected.all data/lm_150000_3_pruned4.0/work/iter1/float.1 data/lm_150000_3_pruned4.0/work/iter1/float.2 data/lm_150000_3_pruned4.0/work/iter1/float.3
Fixing lm-state total 130162 -> 130215
Fixing lm-state total 628196 -> 628425
Fixing lm-state total 98805.7 -> 98830.3
Fixing lm-state total 103377 -> 103403
Fixing lm-state total 935691 -> 936002
Fixing lm-state total 24154.5 -> 24151.8
Fixing lm-state total 183643 -> 183623
Fixing lm-state total 141113 -> 141136
Fixing lm-state total 133343 -> 133370
Fixing lm-state total 24251.2 -> 24247.8
Fixing lm-state total 16812.7 -> 16810.7
Fixing lm-state total 329660 -> 329800
Fixing lm-state total 142554 -> 142569
Fixing lm-state total 90704.6 -> 90744.4
Fixing lm-state total 134375 -> 134419
Fixing lm-state total 134312 -> 134340
Fixing lm-state total 110072 -> 110092
Fixing lm-state total 562274 -> 562477
Fixing lm-state total 393932 -> 394133
Fixing lm-state total 25176 -> 25173.3
Fixing lm-state total 22897.4 -> 22894.9
Fixing lm-state total 29509.4 -> 29505.7
Fixing lm-state total 19654.4 -> 19652.1
Fixing lm-state total 93764.6 -> 93786.7
Fixing lm-state total 99558.3 -> 99584.1
Fixing lm-state total 636152 -> 636299
Fixing lm-state total 212519 -> 212497
Fixing lm-state total 133712 -> 133752
Fixing lm-state total 139033 -> 139059
Fixing lm-state total 10249.8 -> 10248.7
Fixing lm-state total 11838.6 -> 11836.7
Fixing lm-state total 20862.8 -> 20860.7
Fixing lm-state total 32616.2 -> 32611.3
Fixing lm-state total 29350.9 -> 29347.6
Fixing lm-state total 27478.1 -> 27475.3
Fixing lm-state total 82315.7 -> 82346.3
Fixing lm-state total 20680.6 -> 20678.5
Fixing lm-state total 414787 -> 414912
Fixing lm-state total 1.35756e+06 -> 1.35669e+06
Fixing lm-state total 111638 -> 111654
Fixing lm-state total 116167 -> 116195
Fixing lm-state total 20666.4 -> 20664.2
Fixing lm-state total 131420 -> 131445
Fixing lm-state total 757473 -> 757673
Fixing lm-state total 19970.3 -> 19967
Fixing lm-state total 25720.9 -> 25718.2
Fixing lm-state total 87402.3 -> 87425.9
Fixing lm-state total 232604 -> 232578
Fixing lm-state total 94239 -> 94264.2
Fixing lm-state total 11799.4 -> 11798.2
Fixing lm-state total 104053 -> 104081
Fixing lm-state total 77862.1 -> 77886.6
Fixing lm-state total 90543 -> 90583.3
Fixing lm-state total 108433 -> 108484
Fixing lm-state total 109844 -> 109885
Fixing lm-state total 75494.6 -> 75516.1
Fixing lm-state total 109139 -> 109168
float-counts-prune: logprob change per word was -0.0984244 over 7.76452e+07 words.
float-counts-prune: aside from unigram there were 54633092 nonzero n-grams.
Of these 923104 were not pruned because they were shadowed by a higher-order n-gram, and
146733 because they lead to an existing LM-state (according to <protected-counts-input>).
Of the 53563255 n-grams eligible for pruning, 47339085 were actually pruned.
merge-float-counts data/lm_150000_3_pruned4.0/work/iter1/float.1 data/lm_150000_3_pruned4.0/work/iter1/float.2 data/lm_150000_3_pruned4.0/work/iter1/float.3 | float-counts-stats-remove-zeros 150000 /dev/stdin data/lm_150000_3_pruned4.0/work/iter0/stats.all data/lm_150000_3_pruned4.0/work/iter1/float.all data/lm_150000_3_pruned4.0/work/iter1/stats.1 data/lm_150000_3_pruned4.0/work/iter1/stats.2 data/lm_150000_3_pruned4.0/work/iter1/stats.3
float-counts-estimate: logprob per word was -4.76295 over 7.76452e+07 words.
float-counts-estimate: auxiliary function improvement per word was [ 7.4618e-117.76452e+07 -3.6982e+08 0.00579373 0.135179 0.502856 
- 1.74098e-09 + 6.47633e-09 ] = 8.29193e-09
  merge-float-counts: read 1 + 149999 + 9682771 = 9.83277e+06 LM states.
  float-counts-stats-remove-zeros: reduced counts from [ 149999 9774627 44858465 ] = 54783091 to [ 149999 3281933 4012074 ] = 7444006
  merge-float-counts data/lm_150000_3_pruned4.0/work/iter1/stats.1 data/lm_150000_3_pruned4.0/work/iter1/stats.2 data/lm_150000_3_pruned4.0/work/iter1/stats.3 >data/lm_150000_3_pruned4.0/work/iter1/stats.all
  merge-float-counts: lm-state.cc:251: void pocolm::FloatLmState::Check() const: Assertion `fabs(total - my_total) <= 0.0001 \* fabs(my_total)' failed.
  sh: line 1: 11045 Aborted                 (core dumped) merge-float-counts data/lm_150000_3_pruned4.0/work/iter1/stats.1 data/lm_150000_3_pruned4.0/work/iter1/stats.2 data/lm_150000_3_pruned4.0/work/iter1/stats.3 > data/lm_150000_3_pruned4.0/work/iter1/stats.all
  get_objf_and_derivs_split.py: error running command: merge-float-counts data/lm_150000_3_pruned4.0/work/iter1/stats.1 data/lm_150000_3_pruned4.0/work/iter1/stats.2 data/lm_150000_3_pruned4.0/work/iter1/stats.3 >data/lm_150000_3_pruned4.0/work/iter1/stats.all

**Comment by danpovey** [comment]
Thanks... try again, committed another fix.

**Comment by vince62s** [comment]
ok went fine this time. So now how do I get the arpa model ?

**Comment by vince62s** [comment]
forget this I figured out

**Comment by vince62s** [comment]
when I run this:
format_arpa_lm.py data/lm_150000_3_pruned4.0 | gzip -c > data/arpa/150000_3gram_pruned4.0.arpa.gz
I get this : 
validate_vocab.py: validated file data/lm_150000_3_pruned4.0/words.txt with 150000 entries.
validate_lm_dir.py: validated LM directory data/lm_150000_3_pruned4.0
format_arpa_lm.py: running float-counts-to-pre-arpa 3 150000 data/lm_150000_3_pruned4.0/float.all | sort | pre-arpa-to-arpa data/lm_150000_3_pruned4.0/words.txt
float-counts-to-pre-arpa: output [ 150000 1207395 1016081 ] n-grams
pre-arpa-to-arpa: read confusing sequence of lines: ' 2 1 100105    -0.270643' followed by: ' 2 1 100121 -5.54844'... bad counts?
sort: write failed: standard output: Broken pipe
sort: write error
format_arpa_lm.py: command float-counts-to-pre-arpa 3 150000 data/lm_150000_3_pruned4.0/float.all | sort | pre-arpa-to-arpa data/lm_150000_3_pruned4.0/words.txt exited with status 256

**Comment by danpovey** [comment]
I had not tested the conversion to arpa.  Certain assumptions that the arpa-conversion makes may not be met.  I'll have to look into this.

**Comment by vince62s** [comment]
not bad :)

 pruned 4.0 file size 20.4 MB
 file cantab-TEDLIUM/text-test: 1155 sentences, 27512 words, 0 OOVs
 0 zeroprobs, logprob= -66366.6 ppl= 206.579 ppl1= 258.391
 pruned 3.0 file size 25.3 MB
 file cantab-TEDLIUM/text-test: 1155 sentences, 27512 words, 0 OOVs
 0 zeroprobs, logprob= -66162.4 ppl= 203.219 ppl1= 254.013
 pruned 2.0 file size 34.1 MB
 file cantab-TEDLIUM/text-test: 1155 sentences, 27512 words, 0 OOVs
 0 zeroprobs, logprob= -65963.8 ppl= 200.003 ppl1= 249.826
 pruned 1.0 file size 55.7 MB
 file cantab-TEDLIUM/text-test: 1155 sentences, 27512 words, 0 OOVs
 0 zeroprobs, logprob= -65755.2 ppl= 196.679 ppl1= 245.502

 Baseline SRILM
 pruning 1e-7 target file is 26.7 MB
 file cantab-TEDLIUM/text-test: 1155 sentences, 27512 words, 0 OOVs
0 zeroprobs, logprob= -67368.9 ppl= 223.898 ppl1= 281.002
 pruning 5e-8 target file is 46.9 MB
file cantab-TEDLIUM/text-test: 1155 sentences, 27512 words, 0 OOVs
0 zeroprobs, logprob= -66739.2 ppl= 212.855 ppl1= 266.576
 pruning 1e-8 target file is 157.9 MB
file cantab-TEDLIUM/text-test: 1155 sentences, 27512 words, 0 OOVs
0 zeroprobs, logprob= -65995.5 ppl= 200.512 ppl1= 250.489
 pruning 1e-8 target file is 368.5 MB
file cantab-TEDLIUM/text-test: 1155 sentences, 27512 words, 0 OOVs
0 zeroprobs, logprob= -65670.6 ppl= 195.348 ppl1= 243.77

**Comment by francisr** [comment]
Is the baseline SRILM a KN ngram? Under heavy pruning they do worse than GT ngrams.

**Comment by danpovey** [comment]
It would probably make sense to do experiments with GT n-grams as an
additional SRILM.  We'll do them based on perplexity though, it's less
hassle.

**Comment by vince62s** [comment]
I tried to prune the order 4 and the same error popped up.
Am I missing something ?

validate_vocab.py: validated file data/lm_150000_4_pruned1.0/words.txt with 150000 entries.
validate_lm_dir.py: validated LM directory data/lm_150000_4_pruned1.0
format_arpa_lm.py: running float-counts-to-pre-arpa 4 150000 data/lm_150000_4_pruned1.0/float.all | sort | pre-arpa-to-arpa data/lm_150000_4_pruned1.0/words.txt
float-counts-to-pre-arpa: output [ 150000 2993452 3969642 1846861 ] n-grams
pre-arpa-to-arpa: read confusing sequence of lines: ' 2 100 133728  -0.0999543' followed by: ' 2 100 58169 -1.15561'... bad counts?
sort: write failed: standard output: Broken pipe
sort: write error
format_arpa_lm.py: command float-counts-to-pre-arpa 4 150000 data/lm_150000_4_pruned1.0/float.all | sort | pre-arpa-to-arpa data/lm_150000_4_pruned1.0/words.txt exited with status 256
data/arpa/150000_4gram_pruned1.0.arpa.gz: line 176328: reached EOF before \end\
format error in lm file data/arpa/150000_4gram_pruned1.0.arpa.gz

**Comment by danpovey** [comment]
Is your code 100% fully up-to-date and compiled?  I fixed a problem that
was causing that error.
Dan

**Comment by vince62s** [comment]
I know and yes I did, works fine for order 3, fails for order 4

**Comment by vince62s** [comment]
unless I need to redo the counts and such too

**Comment by danpovey** [comment]
Hm, you shouldn't have to re-do the counts.  It will be hard for me to
debug this unless I can reproduce it.  Is there any way you could submit a
PR for commands in one of the checked-in setups that I could use to
reproduce this?  Or just show me the commands if that's easier?

**Comment by vince62s** [comment]
Well I guess the others were able to do it with order on swbd to do their graphs.
for me this one works fine:
prune_lm_dir.py data/lm_150000_3 1.0 data/lm_150000_3_pruned1.0
format_arpa_lm.py data/lm_150000_3_pruned1.0 | gzip -c > data/arpa/150000_3gram_pruned1.0.arpa.gz

and this one fails
prune_lm_dir.py data/lm_150000_4 1.0 data/lm_150000_4_pruned1.0
format_arpa_lm.py data/lm_150000_4_pruned1.0 | gzip -c > data/arpa/150000_4gram_pruned1.0.arpa.gz

If I make a PR with full setup it will be on tedlium and take some time if you want to reproduce it....

**Comment by danpovey** [comment]
I'll try that.  Actually Zhouyang had a problem and I thought his code was
not up-to-date but maybe I was wrong.

**Comment by danpovey** [comment]
OK, I found the problem and fixed it.
Zhouyang, if you were aware there was still a problem even with up-to-date
code, you should have told me.

**Comment by francisr** [comment]
I've done the experiment with a GT 3gram on a corpus of about 1.5B words. 
The test set is: 15480 sentences, 289565 words, 0 OOVs
The SRILM arpa (gzipped) is 2.2G and has ppl= 148.203 ppl1= 193.602.
The pocolm arpa (gzipped) is 3.3G and has ppl= 142.459 ppl1= 185.705

I've pruned them both to 31MB (non gzipped) and I get:
SRILM with SRILM pruning - ppl= 237.539 ppl1= 318.229
pocolm with pocolm pruning - ppl= 222.837 ppl1= 297.515
It appears that SRILM needs arpa files that are about 30-40% bigger than pocolm to match its perplexity when pruning a lot.

Also SRILM's -prune-lowprobs didn't have any effects on pocolm's arpa, so I assume it's already dealt with. I haven't used this flag in my test, so this would make pocolm even better if the goal is to build an HCLG.

**Comment by danpovey** [comment]
Cool- thanks!
Regarding prune-lowprobs, the pocolm LM is "with interpolation".. it it
were a Kneser-Ney model, it would be one "with interpolation", so the
backoff probs are always lower than the direct probs.  So -prune-lowprobs
is expected to have no effect.
BTW, for everyone's info, I am currently working on a mechanism to
completely discount ngrams below a certain count (e.g. 2), like the -gtnmin
options of SRILM, in order to make the LM-building process faster.  It's a
bit complicated because I want to do this only when the total count over
all data sources is less than that value.
Dan

**Comment by francisr** [comment]
The corpus I trained with was entropy filtered from a 4B words one, with the text I used as dev.txt. 
If I train pocolom with the full one, on my test set I get:
Unpruned arpa: ppl= 143.779 ppl1= 187.518 (6.6GB gzipped)
Pruned arpa: ppl= 248.013 ppl1= 333.028 (32MB unzipped)
The unpruned arpa has a similar ppl, but the pruned one is quite worse.

**Comment by vince62s** [comment]
yes but if you prune to the same target size with SRILM from the full corpus it will be even worse, no ?

**Comment by francisr** [comment]
Yes for sure, I was just comparing here pocolm's adaptation to the dev set with entropy filtering.

**Comment by vince62s** [comment]
would we get different results with a 2 steps pruning, e.g., a first pass to bring the full corpus (4B words) to  a 1.5B words LM, and then a second pass to the 32 MB unzipped lm ?

**Comment by danpovey** [comment]
The results would be slightly different.  I would expect the 1-pass pruning
 might be slightly better, but the difference would be very small.

BTW, if the corpus is very large I advise to use min-counts.  There is a
commented-out line in the swbd_fisher run.sh that shows how to do this.

Dan
