### ISSUE TITLE
Error when converting to arpa

### ISSUE THREAD

**Issue by francisr** [danpovey/pocolm#86]
I have trained a 4gram LM, and when I try to convert it to arpa I get this error:
`pre-arpa-to-arpa: read confusing sequence of lines: ' 3 4833 353 2127	-0.00512728' followed by: ' 3 4833 353 2144	-0.00512728'... bad counts?`

What could be the cause of this?

**Comment by francisr** [comment]
As I understand there is a line with the backoff weight, but no line with the weight.  
This 3gram appears only once in my text, and I have a min_counts of 2, so none of these two lines should be there.  
I've been playing with the code that generates the counts though, so it's my fault, but I'd like to know where I should look at to get the correct behaviour.

**Comment by danpovey** [comment]
The issue is that you have a trigram '4833 353 2127' that has a backoff
prob, but that trigram itself does not exist, i.e. there was no count for
'353 4833 -> 2127'.  Such models can't be written in arpa format.
 Anyway, bottom line, there is some assumption about your counts that is
not being satisfied.  Hard to know without knowing how you changed the
counts generation.

**Comment by francisr** [comment]
Thanks, this was indeed the cause of the problem, I managed to fix it.
